apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: myapp-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: myapp.rules
    rules:

    - alert: MyAppHighCPU
      expr: |
        sum(rate(container_cpu_usage_seconds_total{
          namespace="myapp",
          pod=~"myapp-.*"
        }[2m])) > 0.8
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage in myapp"
        description: "CPU usage > 80% for more than 2 minutes"

    - alert: MyAppPodCrashLoop
      expr: |
        increase(kube_pod_container_status_restarts_total{
          namespace="myapp",
          pod=~"myapp-.*"
        }[5m]) > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "myapp pod restarting"
        description: "Pod restarted in last 5 minutes"
